/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PIngApp;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import com.panamahitek.PanamaHitek_MultiMessage; //No se usa, pero podría (NO BORRAR)
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author SaFteiNZz
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    //Variables AUX
    private static PanamaHitek_Arduino ino = new PanamaHitek_Arduino();    
    private static String temperaturaSeteada = "16";
    
    //DATOS BD
    private static Connection conn;
    private static String myDriver = "com.mysql.cj.jdbc.Driver";
    private static String myUrl = "jdbc:mysql://localhost/DBPIng"; //url eloy "jdbc:mysql://localhost/arduino"
    private static String userBD = "safteinzz"; //user eloy "root"
    private static String passBD = "21505519"; //pass eloy ""
    
    //SERIAL ARDUINO
    private static String serialArduino = "COM3";
    /*
    *   Por si fuera necesario recibir varios mensajes
    static PanamaHitek_MultiMessage multi = new PanamaHitek_MultiMessage(4, ino);
    */
    
    //Listener
    private static final SerialPortEventListener listener = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            int recib = 0;
            float esFloat = 0;
            try {
                if (ino.isMessageAvailable()) {                    
                    String recibido = ino.printMessage();  
                    try {
                    	esFloat = Float.parseFloat(recibido);
                        recib = Integer.parseInt(recibido);  
                    } catch (NumberFormatException ex) {
                    }      
                }
            } catch (SerialPortException | ArduinoException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (recib == 1){                
                Date date = Calendar.getInstance().getTime();  
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
                String rn = dateFormat.format(date);  
                
                // Crear query
                String query = "insert into Log_Detecciones(log)" + " values ('" + rn + "')";
                // Preparar el statement
                PreparedStatement statement;
                try {
                    conn = DriverManager.getConnection(myUrl, userBD, passBD);
                    statement = conn.prepareStatement(query);
                    statement.execute();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
            else {
                String Query = "INSERT INTO temperatura (temperatura, temperaturaSeteada) VALUES ('" + esFloat + "','" + temperaturaSeteada + "');";           
            	PreparedStatement preparedStmt;
                try {
                    conn = DriverManager.getConnection(myUrl, userBD, passBD);                    
                    preparedStmt = conn.prepareStatement(Query);
                    preparedStmt.execute();
                    conn.close();
                } catch (SQLException e1) {
                         Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, e1);
                }
            }
        }
    };   
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //Conexion BD        
        try {
            Class.forName(myDriver);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        //Conexion Arduino
        try {
            ino.arduinoRXTX(serialArduino, 9600, listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();     
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCEntrada = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCTemperatura = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonCambiarTemp = new javax.swing.JButton();
        jTextFieldTemperaturaSetter = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxCIncendios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxCPersianas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla de Control");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(670, 350));

        jLabel1.setText("Bienvenido, usuario");

        jLabel2.setText("Estado:");

        jComboBoxCEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desactivado", "Modo Luz", "Modo Alarma" }));
        jComboBoxCEntrada.setActionCommand("comboBoxEntradaChanged");
        jComboBoxCEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control de entrada", jPanel2);

        jLabel7.setText("Estado:");

        jComboBoxCTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desactivado", "Activado" }));
        jComboBoxCTemperatura.setActionCommand("comboBoxEntradaChanged");
        jComboBoxCTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCTemperaturaActionPerformed(evt);
            }
        });

        jLabel3.setText("Temperatura a la cual se encendera la calefacción:");

        jButtonCambiarTemp.setText("Set");
        jButtonCambiarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldTemperaturaSetter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCambiarTemp))
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCambiarTemp)
                    .addComponent(jTextFieldTemperaturaSetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control de temperatura", jPanel3);

        jComboBoxCIncendios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desactivado", "Activado" }));
        jComboBoxCIncendios.setActionCommand("comboBoxEntradaChanged");
        jComboBoxCIncendios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCIncendiosActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCIncendios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCIncendios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control Alarma de incendios", jPanel5);

        jComboBoxCPersianas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desactivado", "Activado" }));
        jComboBoxCPersianas.setActionCommand("comboBoxEntradaChanged");
        jComboBoxCPersianas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCPersianasActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCPersianas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCPersianas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control de Persianas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    //FUNCION PARA ENVIAR STRINGS A ARDUINO
    private void envioArduino(String envio){
        try {        
            ino.sendData(envio);
        } catch (ArduinoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jComboBoxCEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCEntradaActionPerformed
        if (jComboBoxCEntrada.getSelectedIndex() == 0)
        {
            envioArduino("10");
        }
        else if (jComboBoxCEntrada.getSelectedIndex() == 1)
        {
            envioArduino("11");
        }
        else if (jComboBoxCEntrada.getSelectedIndex() == 2)
        {
            envioArduino("12");
        }
        else
        {
            envioArduino("10");
        }            
    }//GEN-LAST:event_jComboBoxCEntradaActionPerformed

    private void jComboBoxCIncendiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCIncendiosActionPerformed
        if (jComboBoxCIncendios.getSelectedIndex() == 0)
        {
            envioArduino("30");
        }
        else if (jComboBoxCIncendios.getSelectedIndex() == 1)
        {
            envioArduino("31");
        }        
        else
        {
            envioArduino("30");
        }
    }//GEN-LAST:event_jComboBoxCIncendiosActionPerformed

    private void jComboBoxCPersianasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCPersianasActionPerformed
        if (jComboBoxCPersianas.getSelectedIndex() == 0)
        {
            envioArduino("40");
        }
        else if (jComboBoxCPersianas.getSelectedIndex() == 1)
        {
            envioArduino("41");
        }        
        else
        {
            envioArduino("40");
        }
    }//GEN-LAST:event_jComboBoxCPersianasActionPerformed

    private void jComboBoxCTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCTemperaturaActionPerformed
        if (jComboBoxCTemperatura.getSelectedIndex() == 0)
        {
            envioArduino("20");
        }
        else if (jComboBoxCTemperatura.getSelectedIndex() == 1)
        {
            envioArduino("21");
        }        
        else
        {
            envioArduino("20");
        }
    }//GEN-LAST:event_jComboBoxCTemperaturaActionPerformed

    private void jButtonCambiarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarTempActionPerformed
        envioArduino("229" + jTextFieldTemperaturaSetter.getText()); //envio de la temperatura al arduino
        temperaturaSeteada = jTextFieldTemperaturaSetter.getText();
        //envioArduino(temperaturaSeteada); //envio de la temperatura al arduino
        infoBox("La temperatura ha sido cambiada a " + jTextFieldTemperaturaSetter.getText() + " satisfactoriamente", "Temperatura Cambiada");
    }//GEN-LAST:event_jButtonCambiarTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarTemp;
    private javax.swing.JComboBox<String> jComboBoxCEntrada;
    private javax.swing.JComboBox<String> jComboBoxCIncendios;
    private javax.swing.JComboBox<String> jComboBoxCPersianas;
    private javax.swing.JComboBox<String> jComboBoxCTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldTemperaturaSetter;
    // End of variables declaration//GEN-END:variables
}
